server:
  port: 8080

spring:
  application:
    name: topicurator

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:topicurator;MODE=MySQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create   # 초기 개발 땐 create, 이후엔 update/validate 권장
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: UTC    # DB에는 UTC로 저장
    database-platform: org.hibernate.dialect.H2Dialect  # H2 사용이므로 H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console

  jackson:
    serialization:
      write-dates-as-timestamps: false

springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /v3/api-docs

jwt:
  secret: "cokothonthisisveryverylongstringsecretkeycokothonthisisveryverylongstringsecretkey"
  access-ttl-min: 15
  refresh-ttl-days: 14

logging:
  level:
    org.springframework.security: INFO
    org.hibernate.SQL: INFO
    org.hibernate.orm.jdbc.bind: TRACE   # 너무 시끄러우면 INFO로 낮추기
