spring:
  application:
    name: topicurator
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/topicurator?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: odte
    password: odte1234
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect